# -*- coding: utf-8 -*-
"""CricketPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEClDi9jjD5T5yN6EZxHDXO1NK2Z3Tpw
"""

import pandas as pd
import pickle
bat = pd.read_csv('Dataset/bat.csv')
bowl_df = pd.read_csv('Dataset/bowl.csv')
ipl_df = pd.read_csv('Dataset/ipl_2022_dataset.csv')

bat.info()

bowl_df.info()

ipl_df.info()

bat.rename(columns={'Runs': 'batRuns','Avg':'batAvg','SR':'batSR'}, inplace=True)
bat_df1 = bat.loc[(bat["Type"] == 'IPL')]
#bat_df2 = bat.loc[(bat["Type"] == 'T20')]
#bat_df = pd.merge(bat_df1,bat_df2,on=["Player"],how="inner")
bat_df1.info()

bowl_df = bowl_df.loc[(bowl_df['Type'] == 'IPL')]
bowl_df.tail()

ipl_df.rename(columns={'COST IN ₹ (CR.)':'Selling_Price'},inplace=True)
ipl_df = ipl_df[['Player','TYPE','Selling_Price']]
ipl_df.head()

playerData = pd.merge(bat_df1,bowl_df,on=["Player","M"],how='inner')
playerData = playerData[['Player','M','batRuns','batAvg','batSR','Wkts','Econ','5W']]
playerData.head()

test = playerData[['M','batRuns','batAvg','batSR','Wkts','Econ','5W']].tail()
test.tail()

import numpy as np
auctionPlayer = pd.merge(playerData,ipl_df,on="Player",how="inner")
auctionPlayer = auctionPlayer.fillna(0)
auctionPlayer['SoldOrNot'] = np.where(auctionPlayer['Selling_Price']>0,1,0)
auctionPlayer = auctionPlayer[['M','batRuns','batAvg','batSR','Wkts','Econ','5W','SoldOrNot']]
auctionPlayer.tail()

# import matplotlib.pyplot as plt
# plt.plot(auctionPlayer['M'],auctionPlayer['SoldOrNot'])

from sklearn.model_selection import train_test_split

X = auctionPlayer.iloc[:, :-1]
y = auctionPlayer.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
X_test

y_test

from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor()
knnr.fit(X_train, y_train)
y_test_pred = knnr.predict(X_test)
y_test_pred

from sklearn.metrics import mean_squared_error

rms = mean_squared_error(y_test, y_test_pred, squared=False)
rms

pickle.dump(knnr,open('model.pkl','wb'))